version: "3.8"

services:
  nginx:
    image: ${DOCKER_USER}/nginx:latest
    services:
  nginx:
    image: ${DOCKER_USER}/nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-1
      - backend-2
    restart: always

  frontend:
    image: ${DOCKER_USER}/frontend:latest
    platform: linux/arm64    
    container_name: frontend-container
    ports:
      - "5173:5173"
    restart: always

  backend-1:
    image: ${DOCKER_USER}/backend:latest
    platform: linux/arm64
    container_name: backend-container-1
    restart: always

  backend-2:
    image: ${DOCKER_USER}/backend:latest
    platform: linux/arm64
    container_name: backend-container-2
    restart: always
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-1
      - backend-2
    restart: always

