name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - qa
    types:
      - closed

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Pull and redeploy
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          set -e

          mkdir -p ~/app/deploy
          cd ~/app/deploy

          curl -f -o docker-compose.yml https://raw.githubusercontent.com/innoetech-dev/my-full-stack-docker-app/refs/heads/feature/pipeline/ci_docker-compose.yml

          sed -i "s|YOUR_DOCKERHUB_USERNAME|$DOCKER_USER|g" docker-compose.yml

          docker compose pull
          docker compose up -d
